<?php
//File translasi antarmuka untuk dukungan multibahasa

$text = array();

if(!isset($_SESSION['username'])){
	$_SESSION['username'] = 'Anom';
}

//English
$en = array (
	0 => "Login",
	1 => "Username",
	2 => "Password",
	3 => "Govinda Rover Web Admin | Robotics AnD Embedded Systems (RADE) STMIK STIKOM Bali",
	4 => "User Authentication",
	5 => "RADE Research Group",
	6 => "Username or password is not valid !",
	7 => "Welcome, ",
	8 => "Input not valid !",
	9 => "GR WebAdmin v0.93",
	10 => "Dashboard",
	11 => "Graph",
	12 => "Environment",
	13 => "Mechanic",
	14 => "Gallery",
	15 => "Configuration",
	16 => "WLAN",
	17 => "WWAN",
	18 => "Control",
	19 => "System",
	20 => "Interface",
	21 => "User",
	22 => $_SESSION['username'],
	23 => "Logout",
	24 => "Govinda Rover (GR) Robot",
	25 => "Not authenticated !",
	26 => "Notification Panel",
	27 => "Control Panel",
	28 => "Camera Feed",
	29 => "Actions",
	30 => "Take Photoshot",
	31 => "Rotate Clockwise",
	32 => "Rotate Counter Clockwise",
	33 => "Close",
	34 => "Open",
	35 => "Download XLS File",
	36 => "Refresh Data",
	37 => "Delete History",
	38 => "Environment Condition",
	39 => "Download File",
	40 => "Refresh Data",
	41 => "Delete History",
	42 => "#",
	43 => "Temperature",
	44 => "Humudition",
	45 => "Time",
	46 => "Speed",
	47 => "Set",
	48 => "Forward",
	49 => "Left",
	50 => "Right",
	51 => "Backward",
	52 => "Stop",
	53 => "Addressing",
	54 => "Upgrade Firmware OTA",
	55 => "Choose file .ino | .pde",
	56 => "Camera Control Panel",
	57 => "D/U",
	58 => "L/R",
	59 => "Lighting Panel",
	60 => "Flash",
	61 => "Laser",
	62 => "On",
	63 => "Off",
	64 => "View Photo",
	65 => "Coordinate values not valid !",
	66 => "PWM value not valid !",
	67 => "Systems halted !",
	68 => "Interrupted !",
	69 => "System Configuration",
	70 => "Camera",
	71 => "Camera Configuration",
	72 => "Resolution",
	73 => "Load Preset",
	74 => "--Choose--",
	75 => "Custom Value",
	76 => "Video Resolution",
	77 => "Video FPS",
	78 => "Photo Resolution",
	79 => "Photo Gallery",	
	80 => "Photo",
	81 => "Photo list",
	82 => "Photo",
	83 => "Video",
	84 => "Edit",
	85 => "Video list",
	86 => "File",
	87 => "Description",
	88 => "Video Gallery",
	89 => "Play",
	90 => "Date",
	91 => "Size",
	92 => "Delete",
	93 => "Reload",
	94 => "File with id ",
	95 => "has deleted",
	96 => "Are you sure to delete the file ?",
	97 => "Record Video",
	98 => "Stop Recording",
	99 => "Recording stopped",
	100 => "Recording started",
	101 => "Input not valid !",
	102 => "System",
	103 => "Temp",
	104 => "Humidity",
	105 => "Carbon Gas",
	106 => "Environment Graph",
	107 => "System Graph",
	108 => "Start",
	109 => "Stop",
	110 => "Value <small>(Temp., Hum., Carbon Gas)</small>",
	111 => "Value <small>(Prosesor, RAM, NetSpeed)</small>",
	112 => "CPU",
	113 => "RAM",
	114 => "Net",
	115 => "Gas",
	116 => "SSID",
	117 => "MAC Address",
	118 => "Quality",
	119 => "Networking",
	120 => "Access Point",
	121 => "IP Address",
	122 => "Network IP Address according to Access Point configuration, device will be accessed through this address.",
	123 => "Example: 192.168.1.10",
	124 => "Subnet Mask",
	125 => "Subnet Mask to determone the network class. If unsure, use 255.255.255.0",
	126 => "Gateway",
	127 => "Gateway address that will be used by the device to connect to the Internet, use Access Point IP Address if unsure",
	128 => "DNS Server",
	129 => "DNS Server address, use 8.8.8.8 if unsure",
	130 => "Example: 192.168.1.1",
	131	=> "Example: 8.8.8.8",
	132 => "Save",
	133 => "Inputted data is invalid !",
	134 => "Configuration has been saved.",
	135 => "!!! SHUTDOWN System !!!",
	136 => "Main SSID",
	137 => "Access Point Configuration",
	138 => "Access Point Service Set Identifier (SSID) that will be used by the device.",
	139 => "Access Point Password, minimum 8 alphanumeric character.",
	140 => "Camera Editor",
	141 => "Scan",
	142 => "Access Point Service Set Identifier (SSID) that will be used by the device for fallback if fail connecting to main SSID.",
	143 => "Backup SSID",
	144 => "User Configuration",
	145 => "Old Username",
	146 => "Old Password",
	147 => "New Username",
	148 => "New Password",
	149 => "New Password Confirmation",
	150 => "Welcome",
	151 => "Access Point",
	152 => "Addressing",
	153 => "User",
	154 => "Finish",
	155 => "Welcome To Govinda Rover Setup Wizard.",
	156 => "From this interface, before using the device, you will be guided to complete the initial platform setup.
			There is three basic setup, the first is network addressing, access point configuration and user data setup.
			To start the wizard, please click next.",
	157 => "Congratulations !",
	158 => "Configuration Finished... Now let's the fun begin",
	159 => "Choose language"
);

//==========================================================================================
//Bahasa Indonesia (id)
//==========================================================================================
$id = array (
	0 => "Masuk",
	1 => "Nama Pengguna",
	2 => "Sandi",
	3 => "Govinda Rover Web Admin | Robotics AnD Embedded Systems (RADE) STMIK STIKOM Bali",
	4 => "User Authentication",
	5 => "RADE Research Group",
	6 => "Nama pengguna atau sandi yang anda masukan tidak valid.",
	7 => "Selamat datang, ",
	8 => "Input tidak valid !",
	9 => "GR WebAdmin v0.93",
	10 => "Dashboard",
	11 => "Grafik",
	12 => "Lingkungan",
	13 => "Mekanik",
	14 => "Galeri",
	15 => "Konfigurasi",
	16 => "WLAN",
	17 => "WWAN",
	18 => "Kontrol",
	19 => "Sistem",
	20 => "Antarmuka",
	21 => "Pengguna",
	22 => $_SESSION['username'],
	23 => "Keluar",
	24 => "Govinda Rover (GR) Robot",
	25 => "Harap lakukan otentikasi diri terlebih dahulu !",
	26 => "Panel Notifikasi",
	27 => "Panel Kontrol",
	28 => "Umpan Kamera",
	29 => "Aksi",
	30 => "Ambil Photoshot",
	31 => "Rotasi Kanan",
	32 => "Rotasi Kiri",
	33 => "Matikan",
	34 => "Nyalakan",
	35 => "Unduh Berkas XLS",
	36 => "Segarkan Data",
	37 => "Hapus Riwayat",
	38 => "Kondisi Lingkungan",
	39 => "Unduh Berkas",
	40 => "Segarkan Data",
	41 => "Hapus Riwayat",
	42 => "#",
	43 => "Suhu",
	44 => "Kelembapan",
	45 => "Waktu Ambil",
	46 => "Kecepatan",
	47 => "Set",
	48 => "Maju",
	49 => "Kiri",
	50 => "Kanan",
	51 => "Mundur",
	52 => "Stop",
	53 => "Pengalamatan",
	54 => "Upgrade Firmware OTA",
	55 => "Pilih file .ino | .pde",
	56 => "Panel Kamera Kontrol",
	57 => "D/U",
	58 => "R/L",
	59 => "Panel Penerangan",
	60 => "Flash",
	61 => "Laser",
	62 => "On",
	63 => "Off",
	64 => "Lihat Foto",
	65 => "Nilai koordinat yang diinput tidak valid.",
	66 => "PWM yang diinput tidak valid.",
	67 => "Sistem dimatikan !",
	68 => "Interrupted !",
	69 => "Konfigurasi Sistem",
	70 => "Kamera",
	71 => "Konfigurasi Kamera",
	72 => "Resolusi",
	73 => "Muat preset",
	74 => "--Pilih--",
	75 => "Nilai kastem",
	76 => "Resolusi video",
	77 => "Video FPS",
	78 => "Resolusi Foto",
	79 => "Galeri Foto",	
	80 => "Foto",
	81 => "Daftar Foto",
	82 => "Foto",
	83 => "Video",
	84 => "Sunting",
	85 => "Daftar Video",
	86 => "File",
	87 => "Keterangan",
	88 => "Galeri Video",
	89 => "Mainkan",
	90 => "Tanggal",
	91 => "Ukuran",
	92 => "Hapus",
	93 => "Muat Ulang",
	94 => "Berkas dengan id",
	95 => "telah dihapus",
	96 => "Yakin ingin menghapus berkas ?",
	97 => "Rekam Video",
	98 => "Stop Perekaman",
	99 => "Perekaman dihentikan",
	100 => "Perekaman dimulai",
	101 => "Input tidak valid !",
	102 => "Sistem",
	103 => "Suhu",
	104 => "Kelembapan",
	105 => "Gas Mudah Terbakar",
	106 => "Grafik Lingkungan",
	107 => "Grafik Sistem",
	108 => "Start",
	109 => "Stop",
	110 => "Nilai <small>(Suhu, Kelembapan, Gas Mudah Terbakar)</small>",
	111 => "Nilai <small>(Prosesor, RAM, NetSpeed)</small>",
	112 => "CPU",
	113 => "RAM",
	114 => "Net",
	115 => "Gas",
	116 => "SSID",
	117 => "Alamat MAC",
	118 => "Kualitas",
	119 => "Jaringan",
	120 => "Access Point",
	121 => "Alamat IP",
	122 => "Alamat jaringan sesuai dengan konfigurasi Access Point, perangkat akan diakses melalui alamat ini.",
	123 => "Contoh: 192.168.1.10",
	124 => "Subnet Mask",
	125 => "Subnet Mask untuk menentukan kelas jaringan. Jika tidak yakin, gunakan 255.255.255.0",
	126 => "Gateway",
	127 => "Alamat gateway yang akan digunakan perangkat untuk menghubung ke internet, gunakan alamat Access Point jika tidak yakin",
	128 => "DNS Server",
	129 => "Alamat DNS Server, gunakan 8.8.8.8 jika tidak yakin",
	130 => "Contoh 192.168.1.1",
	131	=> "Contoh 8.8.8.8",
	132 => "Simpan",
	133 => "Data yang diinput tidak valid !",
	134 => "Pengaturan berhasil disimpan.",
	135 => "!!! MATIKAN System !!!",
	136 => "SSID Utama",
	137 => "Konfigurasi Access Point",
	138 => "Service Set Identifier (SSID) dari jaringan yang akan dihubungi oleh perangkat.",
	139 => "Kata sandi WLAN minimal 8 karakter terdiri dari huruf angka dan simbol standard.",
	140 => "Kamera Editor",
	141 => "Pindai",
	142 => "Service Set Identifier (SSID) dari jaringan yang akan dihubungi oleh perangkat apabila gagal menghubung ke AP utama.",
	143 => "SSID Backup",
	144 => "Pengaturan Pengguna",
	145 => "Nama pengguna lama",
	146 => "Sandi lama",
	147 => "Nama pengguna baru",
	148 => "Sandi baru",
	149 => "Konfirmasi sandi baru",
	150 => "Selamat Datang",
	151 => "Titik Akses",
	152 => "Pengalamatan",
	153 => "Pengguna",
	154 => "Selesai",
	155 => "Selamat datang di Govinda Rover Setup Wizard.",
	156 => "Melalui antarmuka ini, Anda akan dipandu untuk melakukan penyetingan awal platform sebelum dapat digunakan. 
								Penyetingan akan dibagi menjadi tiga tahap yaitu konfigurasi pengalamatan jaringan, titik akses dan data pengguna.
								Untuk memulai wizard, silahkan klik Next.",
	157 => "Congratulations !",
	158 => "Pengaturan selesai... Sekarang let's the fun begin",
	159 => "Pilih Bahasa"
);




///lang logic
if(isset($_SESSION['lang'])){
	//Bahasa Indonesia
	if($_SESSION['lang'] == 'id'){
		$text = $id;
	}	
	//English
	else if($_SESSION['lang'] == 'en'){
		$text = $en;
	}
	//Default English
	else{
		$text = $en;
	}
}

?>